site_name: Dyueee Page
repo_url : https://github.com/Dyueee/Dyueee.github.io
site_author: Dyueee
site_url: https://dyueee.github.io

nav: 
  - 主页: index.md
  - 文档:
    - git操作指南: Tutorial/git操作指南.md
    - mkdocs操作指南: Tutorial/mkdocs操作指南.md
  - 笔记: Tutorial/笔记.md
  - 关于: about.md

# plugins:
#   social:
#     cards_layout_options:
#       background_color: red             # Change background color
#       background_image: null             # Remove background image

theme:
  name: material # https://squidfunk.github.io/mkdocs-material/
  logo: assets/logo.png
  repo: fontawesome/brands/github
  features:
    - content.code.copy # 代码复制
    - content.code.annotate # 代码注释
    - navigation.instant # 快速跳转
    - navigation.indexes # 索引
    - navigation.top 
    - search.suggest
    - search.highlight
  palette:
    scheme: slate # 夜间模式
    primary: blue grey # 主题色
    accent: orange # 侧边栏颜色
  palette:
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Roboto # 正文字体
    code: Roboto Mono # 代码字体


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - footnotes
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta # 支持Markdown文件上方自定义标题标签等